mi:
	python3 manage.py migrate

mm:
	python3 manage.py makemigrations

rs:
	python3 manage.py runserver

rsp:
	python3 manage.py runserver_plus --cert-file cert.crt

st:
	migrate runserver

sh:
	python3 manage.py shell

dd:
	python3 manage.py dumpdata --indent=2 --output=mysite_data.json

test:
	python3 manage.py test

docker:
	docker start edb52e3b5305